version: '3.9'
name: tp0

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
      - ./protocol/protocol.ini:/protocol.ini

  client1: &client # https://docs.docker.com/compose/compose-file/#fragments
    container_name: client1
    image: client_py:latest
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - NOMBRE=Lionel
      - APELLIDO=Messi
      - DOCUMENTO=18122022
      - NACIMIENTO=1987-06-24
      - NUMERO=1010
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client_py/config.ini:/config.ini
      - ./protocol/protocol.ini:/protocol.ini
